[package]
name = "runtime"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rust_runtime"
path = "src/lib.rs"
bench = false

[dependencies]
bitvec = "0.22"

[dependencies.num-bigint]
version = "0.3"

[dependencies.rug]
version = "1.13"
default-features = false
features = ["integer"]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "zarith_bench"
harness = false

[[bench]]
name = "builder_bench"
harness = false

[[bench]]
name = "parser_bench"
harness = false